apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'argocd'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/adnan-kobir-sp/argocd.git
