apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ctrl-dev-use1
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/adnan-kobir-sp/argocd.git
  - https://github.com/adnan-kobir-sp/k8s-resources.git
